### ISSUE TITLE
frontmatter.<key> not displaying boolean values

### ISSUE THREAD

**Issue by tallguyjenks** [jplattel/open-note-to-window-title#14]
randomly tried to display frontmatter.publish to get the false in the title but it doesn't work with boolean values only strings

<details>
<summary>Boolean as Boolean</summary>

![image](https://user-images.githubusercontent.com/29872822/130488887-84c369a8-7469-4337-9e5e-94d080b081f3.png)

</details>

<details>
<summary>Boolean as string</summary>

![image](https://user-images.githubusercontent.com/29872822/130488844-f69ec147-449c-4355-8015-717d97ec9aa9.png)

</details>

**Comment by luckman212** [comment]
Hmm, that's an interesting one. Thanks @tallguyjenks 

I just pushed a fix, if you build from PR #11 you can test it.

**Comment by luckman212** [comment]
Hey :wave: @tallguyjenks since 0.3.1 has been released, wondering if this issue is solved for you now?

**Comment by tallguyjenks** [comment]
i cant believe i didnt get notified of this or just ignored it somehow, but in going through my old issues on here, yes, i just tested and it works as expected now ✅️
