### ISSUE TITLE
Maybe a bug?

### ISSUE THREAD

**Issue by Quorafind** [jplattel/open-note-to-window-title#3]
When I used `open note to window title` plugin, and at the same time I installed another plugin named `search on the internet` ; When I used the iframe feature to search stuff in Obsidian, and then I used hotkey to close the iframe windows the latter plugin created. The left sidebar would be toggled and show (if it is hided before)

**Comment by jplattel** [comment]
I don't think this is a bug with this plugin. I don't modify any keys or functionality. 

It might be a double assignment of hotkeys or something but surely not this plugin. Did you also file a bug request at the other plugin?

**Comment by Quorafind** [comment]
@jplattel Oh, sorry, I will file a issue on another plugin. So that I close this issue now.
