### ISSUE TITLE
Feature Request: Ability to display metadata in window title

### ISSUE THREAD

**Issue by austinsmoss** [jplattel/open-note-to-window-title#6]
It would be extremely helpful if this plugin had an option to grab metadata from the open note and display it in the window title. For people who track their time using automated time trackers (e.g., ActivityWatcher) this feature would allow them to track time spent across different categories of notes. This use-case is what caused me to think about this feature request.

Here is my full post on the Discord server that provides a little more detail:

> I am trying to track the amount of time that I work on certain types of notes (e.g., evergreen, source, technical, or any other classification you want). 
>
> My current best idea for how to do this is to use an automated time tracking app  (e.g., ActivityWatcher), which uses window titles to categorize activity. Thus, I need a way to determine note type from the text in the Window Title.
>
> If I followed a specific note naming convention (e.g., all source notes start with a "!" or similar idea) then this could be possible using the features currently available in the Open Note to Window Title plug-in (https://github.com/jplattel/open-note-to-window-title by @jplattel). However, simply using note names seems somewhat restrictive in the long run (limits number of different categorizations and susceptible to future changes in workflow) and specific to my use case of tracking time by note type. 
>
> A more flexible method, if possible, would be to add the text of certain metadata to the Window Title. For example, adding a note's tags data would allow me to categorize my time based on anything that I add as a tag. Using a custom YAML key name would be even more flexible. Is this possible?

**Comment by jplattel** [comment]
Alright! With the just released 0.2.0 you can set a window title based on frontmatter data in a note! For example, if a note contains the following frontmatter:

```yaml
category: 'test'
```

You can use that as in the template for open files like: `Obsidian: {category}`

I think this solves your question am I right? :)

**Comment by austinsmoss** [comment]
This is exactly the functionality I wanted, and it is working great! I also like the additional options you provided.

Thanks for incorporating this.
