### ISSUE TITLE
Mind changing the sequence or make it templatable?

### ISSUE THREAD

**Issue by Moonbase59** [jplattel/open-note-to-window-title#7]
Most people expect the window title to go from the smallest to the largest entity, like "file – vault – app". On smaller windows, the title would also be in front, thus recognizable. Btw, all browsers do it like this.

Would you mind changing that?

Or make it templatable in the settings, like doing something on the lines of

```text
{{filename}} – {{vault}} – {{app}}
```

If so, it might be nice to have _two_ "file" templates: One for the file "title" (just filename, without extension) and one for the full file path (including extension).

**Comment by jroachgit** [comment]
Thanks Moonbase59.
Also, thinking about filename +/- extension +/- folderpath in front or also available as a separate tag.

**Comment by Moonbase59** [comment]
Not a bad idea. One could construct whatever one wanted then.

**Comment by Moonbase59** [comment]
1. Referring to a discussion on the Discord: Better use `{{…}}` syntax for the templating, since Obsidian’s _Templates_ does and other plugins like _Dictionary_ use the "moustache-style", too.

2. Could we also please have something like `{{filetitle}}` (not the actual title but the filename without `.md` if Markdown, but _with_ extension otherwise), in the style Obsidian displays it)?

**Comment by jplattel** [comment]
Thanks @Moonbase59! I've just pushed 0.2.1 with support for moustache templates and frontmatter re-keyed to `frontmatter.<key>`: https://github.com/jplattel/open-note-to-window-title/releases/tag/0.2.1

As for point 2, that should be easy to implement! Scheduling that for the next version!

**Comment by Moonbase59** [comment]
Fantastic speed, thanks a bundle!

Just one more … sorry: Original Obsidian shows its version number. Considering the speed of updating, that _is_ useful. So maybe let’s have an `{{app}}` that would fill with `Obsidian 0.12.12`, like Obsidian itself does?

**Comment by jplattel** [comment]
Ah yeah, I'll include the origin basetitle as {{basetitle}}. Or if the version is available somewhere I'll get it there! Should be good!

**Comment by Moonbase59** [comment]
Otherwise already works great! Will be a delight for ActivityWatcher users!

**Comment by jroachgit** [comment]
Yes - I use Toggl for my activity watching.
I will add Toggl's API to my todo to see about having a toggl button in Obsidian to start timing based on the notes title/meta data (maybe?).

**Comment by luckman212** [comment]
This is a really great feature add - thanks @jplattel and @Moonbase59 for the ideas!

Would it be possible to adjust the behavior so that if an attribute is null, to omit the separator?

e.g. if your template was
```
{{filename}} – {{client}} - {{project}} – {{app}}
```

but the note did not have a `project:` assigned in YAML, it would just show up as
```
Meeting Notes 2021-08-05.md - QuuxCo - Obsidian
```

Basically, add a separate field for `separator` and then just use a `join()` on the moustache elements, omitting any nulls...
This would prevent ugly titles like `Meeting Notes 2021-08-05.md - QuuxCo -  - Obsidian`

**Comment by Moonbase59** [comment]
I also thought about that, but for a simple window title this might be "overstructuring it". It’s also rather impossible to outguess what people might put in their titles, like `– my wonderful :paintbrush: Obsidian –` or the like. If using fixed fields and a joiner, this might be lost. Or they might decide on different field separators, to find things in the title with watcher apps …

It looks odd if a field is empty, I agree, but at least you _see_ there’s something left out: "Oh, it’s not assigned to a project yet!" in your example above.

Just guess we can’t have everything. But _what_ we got is already a great improvement, and I thank @jplattel for being that open-minded and fast!

**Comment by luckman212** [comment]
@Moonbase59 and @jplattel I came up with a reasonable solution (I think) and just submitted PR #10 for it. 

It adds a setting for **separator** string (can be anything, but defaults to ` - `) and allows for dynamic removal of unpopulated moustache templates to keep the title clean. Another small QoL improvement is I made the settings fields larger so they don't cut off, and set them to `monospace` type.

To use it, separate your `{{moustache}}` placeholders with `%%` to have the separator dynamically inserted. 

Curious to know your thoughts!

**Comment by Moonbase59** [comment]
@luckman212 Wouldn’t introduce _yet another "syntax"_. Using what Obsidian misuses as "comment" in a non-standard way now to hold a template variable seems confusing.

If using some separator template, why not `{{sep}}`, `{{separator}}` or something? You could then build stuff like `{{filename}}{{sep}}{{whatever}}`.

How would you decide if to show the separator? Only if (expanded) string has content at the adjacent left _and_ right sides, I presume?

Anyway. Whatever.

**Comment by luckman212** [comment]
@Moonbase59 sure, the separator string could be anything. I chose `%%` because it's a literal string that no one would likely need to actually appear in the title. Yes it could be `{{sep}}` I suppose, but I wanted the separator string to be visually distinct from the placeholders... plus, it's shorter :) 

As for how it decides when to insert the separator, yes you can look at the code... it's pretty simple. It uses a regex replacement to match only if the placeholder has a value. This way no extra whitespace or dangling separators are created.

**Comment by Moonbase59** [comment]
@luckman212 Yeah, I can see the idea behind it, and it certainly has its use case. It _could_ be kinda "switched" off by not using the `%%`, right`(For people that prefer an "empty field".)

**Comment by luckman212** [comment]
@Moonbase59 Hmm. You bring up a good point about having the option to preserve the whitespace. I'm finalizing an update now that adds this, as well as adds the ``{{version}}` placeholder you asked for.

**Comment by luckman212** [comment]
Pretty sure most if not all of the issues brought up here have been addressed. Feel free to test & comment on #11.

**Comment by Moonbase59** [comment]
Yeah, I agree. So maybe #11 can be merged and we get another great official version?

**Comment by jplattel** [comment]
0.3.1 is now officially released: https://github.com/jplattel/open-note-to-window-title/releases/tag/0.3.1

Closing this issue for now! If you find any new bugs, feel free to open a new issue :)
